### PR TITLE
fix int queries

### LINKED ISSUE #28: cannot search users by uidnumber
When running EOS the OS needs to look up the user by the numeric uid. This fails with the glauth ocis-accounts backend:
```
ldapsearch -x -H ldap://localhost:9125 -b dc=example,dc=org -D "cn=reva,dc=example,dc=org" -w reva '(&(objectclass=posixAccount)(uidnumber=20000))'                                   
# extended LDIF
#
# LDAPv3
# base <dc=example,dc=org> with scope subtree
# filter: (&(objectclass=posixAccount)(uidnumber=20000))
# requesting: ALL
#

# search result
search: 2
result: 0 Success

# numResponses: 1
```

might be an ocis-accounts problem

server log
```
2020-07-24T18:00:18+02:00 DBG Bind request basedn=dc=example,dc=org binddn=cn=reva,dc=example,dc=org service=glauth src={"IP":"::1","Port":52050,"Zone":""}
2020-07-24T18:00:18+02:00 DBG using query query={"conjuncts":[{"field":"bleve_type","term":"account"},{"field":"on_premises_sam_account_name","term":"reva"}]} service=accounts
2020-07-24T18:00:18+02:00 DBG result result={"facets":null,"hits":[{"id":"bc596f3c-c955-4328-80a0-60d018b4ad57","index":"/var/tmp/ocis-accounts/index.bleve","score":3.4921022015832683,"sort":["_score"]}],"max_score":3.4921022015832683,"request":{"explain":false,"facets":null,"fields":null,"from":0,"highlight":null,"includeLocations":false,"query":{"conjuncts":[{"field":"bleve_type","term":"account"},{"field":"on_premises_sam_account_name","term":"reva"}]},"search_after":null,"search_before":null,"size":10,"sort":["-_score"]},"status":{"failed":0,"successful":1,"total":1},"took":31318,"total_hits":1} service=accounts
2020-07-24T18:00:18+02:00 DBG found account account={"accountEnabled":true,"displayName":"Reva Inter Operability Platform","gidNumber":"15000","id":"bc596f3c-c955-4328-80a0-60d018b4ad57","mail":"storage@example.org","memberOf":[{"id":"34f38767-c937-4eb6-b847-1c175829a2a0"}],"onPremisesSamAccountName":"reva","passwordProfile":{"password":"***REMOVED***"},"preferredName":"reva","uidNumber":"10001"} service=accounts
2020-07-24T18:00:18+02:00 DBG Bind success binddn=cn=reva,dc=example,dc=org service=glauth src={"IP":"::1","Port":52050,"Zone":""}
2020-07-24T18:00:18+02:00 DBG Search request basedn=dc=example,dc=org binddn=cn=reva,dc=example,dc=org filter=(&(objectclass=posixAccount)(uidnumber=20000)) service=glauth src={"IP":"::1","Port":52050,"Zone":""}
2020-07-24T18:00:18+02:00 DBG parsed query basedn=dc=example,dc=org binddn=cn=reva,dc=example,dc=org filter=(&(objectclass=posixAccount)(uidnumber=20000)) qtype=users query="uid_number eq '20000'" service=glauth
2020-07-24T18:00:18+02:00 DBG using query query={"conjuncts":[{"field":"bleve_type","term":"account"},{"field":"uid_number","term":"20000"}]} service=accounts
2020-07-24T18:00:18+02:00 DBG result result={"facets":null,"hits":[],"max_score":0,"request":{"explain":false,"facets":null,"fields":null,"from":0,"highlight":null,"includeLocations":false,"query":{"conjuncts":[{"field":"bleve_type","term":"account"},{"field":"uid_number","term":"20000"}]},"search_after":null,"search_before":null,"size":10,"sort":["-_score"]},"status":{"failed":0,"successful":1,"total":1},"took":25814,"total_hits":0} service=accounts
2020-07-24T18:00:18+02:00 DBG AP: Search OK basedn=dc=example,dc=org binddn=cn=reva,dc=example,dc=org filter=(&(objectclass=posixAccount)(uidnumber=20000)) service=glauth src={"IP":"::1","Port":52050,"Zone":""}
```

### PR DESCRIPTION
**Pull request by butonic**
- [x] changelog

partly fixes https://github.com/owncloud/ocis-glauth/issues/28 by sending the uidnumber and gidnumber as numeric literals instead of strings

### CODE REVIEW

**Review by kulmann — APPROVED** [review]

File: pkg/server/glauth/handler.go [hunk 1]
```diff
@@ -330,9 +331,9 @@ func parseFilter(f *ber.Packet) (qtype queryType, q string, err error) {
 		case "displayname":
 			q = fmt.Sprintf("display_name eq '%s'", escapeValue(value))
 		case "uidnumber":
-			q = fmt.Sprintf("uid_number eq '%s'", escapeValue(value))
+			q = fmt.Sprintf("uid_number eq %s", value) // TODO check it is a number?
```
Comment (refs) [inline pkg/server/glauth/handler.go]: That todo can potentially come back in the future and bite us. Why not addressing it here? [There's this](https://golang.org/pkg/strconv/#ParseInt)

**Review by refs — CHANGES_REQUESTED** [review]

**Review by refs — APPROVED** [review]
